version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/integration
  - source: /
    destination: /var/www/html
  - source: /
    destination: /opt/codedeploy-agent
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

