version: 0.0
os: linux
files:
  - source: /app.js
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 800
      runas: root
    - location: scripts/start_server
      timeout: 800
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 800
      runas: root

